### ISSUE TITLE
terminate

### ISSUE THREAD

**Issue by drmaq** [formcore/silty_ui#1]
How do you terminate the program?

**Comment by samule-i** [comment]
Currently there's no in-app way of doing so, it must be terminated through SSH or through the processor list.

I'll add a way to close the program and upload it later.

...

Alright, there should now be an exit button in the top right hand of the screen, originally I decided not to put it on because I was intending to use this as a kiosk and manage remotely, but until something is in place to easily close it, I guess I do need a way to kill it without a ton of trouble.

Thanks for bringing it up.

**Comment by drmaq** [comment]
Thanks, no problem.
